
//TICKETS
//TRAER TICKETS
export const COMENZAR_DESCARGA_TICKETS = 'COMENZAR_DESCARGA_TICKETS';
export const DESCARGA_TICKETS_EXITO = 'DESCARGA_TICKETS_EXITO';
export const DESCARGA_TICKETS_ERROR = 'DESCARGA_TICKETS_ERROR';

//AGREGAR TICKETS
export const AGREGAR_TICKET = 'AGREGAR_TICKET';
export const AGREGAR_TICKET_EXITO = 'AGREGAR_TICKET_EXITO';
export const AGREGAR_TICKET_ERROR = 'AGREGAR_TICKET_ERROR';


//AUTENTICACION
export const AUTENTICAR_USUARIO = 'AUTENTICAR_USUARIO';
export const AUTENTICAR_USUARIO_EXITO = 'AUTENTICAR_USUARIO_EXITO';
export const AUTENTICAR_USUARIO_ERROR = 'AUTENTICAR_USUARIO_ERROR';
export const CERRAR_SESION_USUARIO = 'CERRAR_SESION_USUARIO'

//ALERTAS
export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';

