
//TICKETS
//TRAER TICKETS
export const TRAER_TICKET = 'TRAER_TICKET';
export const TRAER_TICKET_EXITO = 'TRAER_TICKET_EXITO';
export const TRAER_TICKET_ERROR = 'TRAER_TICKET_ERROR';

//AGREGAR TICKETS
export const AGREGAR_TICKET = 'AGREGAR_TICKET';
export const AGREGAR_TICKET_EXITO = 'AGREGAR_TICKET_EXITO';
export const AGREGAR_TICKET_ERROR = 'AGREGAR_TICKET_ERROR';


//AUTENTICACION
export const INICIAR_LOGIN = 'INICIA_LOGIN';
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';

