
//#region TICKETS

//TRAER TICKETS
export const COMENZAR_DESCARGA_TICKETS = 'COMENZAR_DESCARGA_TICKETS';
export const DESCARGA_TICKETS_EXITO = 'DESCARGA_TICKETS_EXITO';
export const DESCARGA_TICKETS_ERROR = 'DESCARGA_TICKETS_ERROR';

//AGREGAR TICKETS
export const AGREGAR_TICKET = 'AGREGAR_TICKET';
export const AGREGAR_TICKET_EXITO = 'AGREGAR_TICKET_EXITO';
export const AGREGAR_TICKET_ERROR = 'AGREGAR_TICKET_ERROR';


//EDITAR TICKET
export const OBTENER_TICKET_EDITAR = 'OBTENER_TICKET_EDITAR';
export const COMENZAR_EDICION_TICKET = 'COMENZAR_EDICION_TICKET';
export const TICKET_EDITADO_EXITO = 'TICKET_EDITADO_EXITO';
export const TICKET_EDITADO_ERROR = 'TICKET_EDITADO_ERROR';

//OBTENER ESTADISTICA TICKET ULTIMOS 30 DIAS

export const ESTADISTICA_TICKETS = 'ESTADISTICA_TICKETS';
export const ESTADISTICA_TICKETS_EXITO = 'ESTADISTICA_TICKETS_EXITO';
export const ESTADISTICA_TICKETS_ERROR = 'ESTADISTICA_TICKETS_ERROR';


//#endregion

//#region AUTENTICACION

//AUTENTICACION
export const AUTENTICAR_USUARIO = 'AUTENTICAR_USUARIO';
export const AUTENTICAR_USUARIO_EXITO = 'AUTENTICAR_USUARIO_EXITO';
export const AUTENTICAR_USUARIO_ERROR = 'AUTENTICAR_USUARIO_ERROR';
export const CERRAR_SESION_USUARIO = 'CERRAR_SESION_USUARIO'
export const USUARIO_AUTENTICADO = 'USUARIO_AUTENTICADO'

//#endregion

//#region ALERTAR

export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';

//#endregion

//#region  DEPENDENCIAS

//OBTENER DEPENDENCIAS
export const COMENZAR_DESCARGA_DEPENDENCIAS = 'COMENZAR_DESCARGA_DEPENDENCIAS';
export const DESCARGA_DEPENDENCIAS_EXITO = 'DESCARGA_DEPENDENCIAS_EXITO';
export const DESCARGA_DEPENDENCIAS_ERROR = 'DESCARGA_DEPENDENCIAS_ERROR';

//#endregion

//#region CATEGORIAS

//OBTENER CATEGORIAS
export const COMENZAR_DESCARGA_CATEGORIAS = 'COMENZAR_DESCARGA_CATEGORIAS';
export const DESCARGA_CATEGORIAS_EXITO = 'DESCARGA_CATEGORIAS_EXITO';
export const DESCARGA_CATEGORIAS_ERROR = 'DESCARGA_CATEGORIAS_ERROR';

//#endregion

//#region MENSAJES

//AGREGAR MENSAJES
export const AGREGAR_MENSAJE = 'AGREGAR_MENSAJE';
export const AGREGAR_MENSAJE_EXITO = 'AGREGAR_MENSAJE_EXITO';
export const AGREGAR_MENSAJE_ERROR = 'AGREGAR_MENSAJE_ERROR';

//OBTENER MENSAJES
export const COMENZAR_DESCARGA_MENSAJES = 'COMENZAR_DESCARGA_MENSAJES';
export const DESCARGA_MENSAJES_EXITO = 'DESCARGA_MENSAJES_EXITO';
export const DESCARGA_MENSAJES_ERROR = 'DESCARGA_MENSAJES_ERROR';

//#endregion

//#region 

//OBTENER INVENTARIO
export const COMENZAR_DESCARGA_INVENTARIO = 'COMENZAR_DESCARGA_INVENTARIO';
export const DESCARGA_INVENTARIO_EXITO = 'DESCARGA_INVENTARIO_EXITO';
export const DESCARGA_INVENTARIO_ERROR = 'DESCARGA_INVENTARIO_ERROR';

//#endregion

//#region USUARIOS

//OBTENER USUARIOS
export const COMENZAR_DESCARGA_USUARIOS = 'COMENZAR_DESCARGA_USUARIOS';
export const DESCARGA_USUARIOS_EXITO = 'DESCARGA_USUARIOS_EXITO';
export const DESCARGA_USUARIOS_ERROR = 'DESCARGA_USUARIOS_ERROR';

//CREAR USUARIO

export const AGREGAR_USUARIO = 'USUARIO_TICKET';
export const AGREGAR_USUARIO_EXITO = 'AGREGAR_USUARIO_EXITO';
export const AGREGAR_USUARIO_ERROR = 'AGREGAR_USUARIO_ERROR';

//EDITAR TICKET
export const GUARDAR_USUARIO_EDITAR = 'GUARDAR_USUARIO_EDITAR';
export const COMENZAR_EDICION_USUARIO = 'COMENZAR_EDICION_USUARIO';
export const USUARIO_EDITADO_EXITO = 'USUARIO_EDITADO_EXITO';
export const USUARIO_EDITADO_ERROR = 'USUARIO_EDITADO_ERROR';

//#endregion


